### ISSUE TITLE
Error 500 when Scan Network

### ISSUE THREAD

**Issue by WootEpix** [allegro/ralph#1137]
Hello, 

I Encounter an error when performing Network scan : 

ERROR   [MainProcess 19886] base - Internal Server Error: /ui/networks/1/scan/192.168.XX.XX/
Traceback (most recent call last):
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 109, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/account/models.py", line 273, in inner_decorator
    return func(self, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/ui/views/common.py", line 196, in dispatch
    return super(ACLGateway, self).dispatch(*args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/ui/views/common.py", line 1538, in post
    ip_address, plugins, automerge=False, called_from_ui=True
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/scan/manual.py", line 71, in queue_scan_address
    queue = django_rq.get_queue(queue_name)
  File "/home/ralph/local/lib/python2.7/site-packages/django_rq/queues.py", line 38, in get_queue
    return Queue(name, connection=get_connection(name))
  File "/home/ralph/local/lib/python2.7/site-packages/django_rq/queues.py", line 23, in get_connection
    return get_redis_connection(QUEUES[name])
KeyError: u'test'

regards.

**Comment by mkurek** [comment]
Nothing more to add. Closing.
