### ISSUE TITLE
ralph cmdb_sync --action=import --kind=ci ImportError: cannot import name create_api_key

### ISSUE THREAD

**Issue by djbdjb00djb** [allegro/ralph#1254]
(ralph)ralph@it-ralph:~$ ralph cmdb_sync --action=import --kind=ci
Traceback (most recent call last):
  File "/home/ralph/bin/ralph", line 9, in <module>
    load_entry_point('ralph==2.1.0', 'console_scripts', 'ralph')()
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/__main__.py", line 56, in main
    execute_from_command_line(sys.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 69, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/ralph/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/cmdb/management/commands/cmdb_sync.py", line 11, in <module>
    from ralph.cmdb.importer import CIImporter
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/cmdb/importer.py", line 52, in <module>
    import ralph.discovery.models as db
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/discovery/models.py", line 11, in <module>
    from ralph.discovery.models_device import (
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/discovery/models_device.py", line 40, in <module>
    from ralph.util.models import SyncFieldMixin
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/util/models.py", line 15, in <module>
    from tastypie.models import create_api_key
ImportError: cannot import name create_api_key

**Comment by vi4m** [comment]
Which ralph version do you use?

**Comment by vi4m** [comment]
We provide some support directly on the guitar channel - i sent you invitation

**Comment by djbdjb00djb** [comment]
I'm use  ralph 2.1.0 upgrad from 2.0.0 , but when I A fresh install，it's OK;

**Comment by vi4m** [comment]
We've released new version which fixes this issue http://ralph.readthedocs.org/en/latest/changes.html

**Comment by mkurek** [comment]
Fixed.
