### ISSUE TITLE
ralph migrate ralph_assets  depends on unmigrated application 'cmdb'

### ISSUE THREAD

**Issue by djbdjb00djb** [allegro/ralph#1255]
A fresh install Ralph 2.1.0 in Ubuntu 14.04.1

reference http://ralph.allegrogroup.com/doc/installation.html 

(ralph)$ pip install ralph --use-mirrors --allow-all-external --allow-unverified ipaddr --allow-unverified postmarkup --allow-unverified python-graph-core --allow-unverified pysphere

(ralph)$ ralph makeconf

(ralph)$ ralph syncdb --all

(ralph)$ ralph migrate --fake

(ralph)$ ralph collectstatic -l

(ralph)$ ralph cmdb_sync --action=import --kind=ci

(ralph)$ ralph cmdb_sync --action=import --kind=all-relations

(ralph)$ pip install ralph_assets

(ralph)$ add a line in settings：PLUGGABLE_APPS = ['assets',]

(ralph)$ ralph migrate ralph_assets
Traceback (most recent call last):
  File "/home/ralph/bin/ralph", line 9, in <module>
    load_entry_point('ralph==2.1.0', 'console_scripts', 'ralph')()
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/__main__.py", line 56, in main
    execute_from_command_line(sys.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/ralph/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 108, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/__init__.py", line 166, in migrate_app
    Migrations.calculate_dependencies()
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/base.py", line 228, in calculate_dependencies
    migration.calculate_dependencies()
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/base.py", line 362, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/base.py", line 346, in _get_dependency_objects
    raise exceptions.DependsOnUnmigratedApplication(self, app)
south.exceptions.DependsOnUnmigratedApplication: Migration 'business:0006_auto__del_ventureowner__add_field_venturerole_path' depends on unmigrated application 'cmdb'.

**Comment by djbdjb00djb** [comment]
set PLUGGABLE_APPS = ['assets’,’cmdb’] can run command ralph migrate cmdb ;

**Comment by mkurek** [comment]
you should add 'cmdb' to PLUGGABLE_APPS before running `ralph syncdb --all`
