### ISSUE TITLE
Error in migration: ralph_assets:0017_auto__del_assethistorychange__del_licencehistorychange__del_supporthis

### ISSUE THREAD

**Issue by djbdjb00djb** [allegro/ralph#1256]
A fresh install Ralph 2.1.0 in Ubuntu 14.04.1

reference http://ralph.allegrogroup.com/doc/installation.html

(ralph)$ pip install ralph --use-mirrors --allow-all-external --allow-unverified ipaddr --allow-unverified postmarkup --allow-unverified python-graph-core --allow-unverified pysphere

(ralph)$ ralph makeconf

(ralph)$ ralph syncdb --all

(ralph)$ ralph migrate --fake

(ralph)$ ralph collectstatic -l

(ralph)$ pip install ralph_assets

(ralph)$ add a line in settings：PLUGGABLE_APPS = ['assets','cmdb']

(ralph)$ ralph migrate cmdb

(ralph)$ $ ralph migrate ralph_assets 
Running migrations for ralph_assets:
 - Migrating forwards to 0017_auto__del_assethistorychange__del_licencehistorychange__del_supporthis.
 > ralph_assets:0017_auto__del_assethistorychange__del_licencehistorychange__del_supporthis
FATAL ERROR - The following SQL query failed: CREATE TABLE `ralph_assets_history` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `date` datetime NOT NULL, `user_id` integer NULL, `content_type_id` integer NOT NULL, `object_id` integer UNSIGNED NOT NULL, `field_name` varchar(64) NOT NULL, `old_value` longtext NOT NULL, `new_value` longtext NOT NULL);
The error was: (1050, "Table 'ralph_assets_history' already exists")
 ! Error found during real run of migration! Aborting.

 ! Since you have a database that does not support running
 ! schema-altering statements in transactions, we have had 
 ! to leave it in an interim state between migrations.

! You *might* be able to recover with:   = DROP TABLE `ralph_assets_history` CASCADE; []
   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `ralph_assets_asset` DROP COLUMN `service_id` CASCADE; []
   - no dry run output for delete_foreign_key() due to dynamic DDL, sorry
   = ALTER TABLE `ralph_assets_asset` DROP COLUMN `device_environment_id` CASCADE; []

 ! The South developers regret this has happened, and would
 ! like to gently persuade you to consider a slightly
 ! easier-to-deal-with DBMS (one that supports DDL transactions)
 ! NOTE: The error which caused the migration to fail is further up.
Error in migration: ralph_assets:0017_auto__del_assethistorychange__del_licencehistorychange__del_supporthis
Traceback (most recent call last):
  File "/home/ralph/bin/ralph", line 9, in <module>
    load_entry_point('ralph==2.1.0', 'console_scripts', 'ralph')()
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/__main__.py", line 56, in main
    execute_from_command_line(sys.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(*args, **options)
  File "/home/ralph/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 108, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/__init__.py", line 213, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/migrators.py", line 235, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/migrators.py", line 310, in migrate_many
    result = self.migrate(migration, database)
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration)
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/migrators.py", line 107, in run
    return self.run_migration(migration)
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/migrators.py", line 81, in run_migration
    migration_function()
  File "/home/ralph/local/lib/python2.7/site-packages/south/migration/migrators.py", line 57, in <lambda>
    return (lambda: direction(orm))
  File "/home/ralph/local/lib/python2.7/site-packages/ralph_assets/migrations/0017_auto__del_assethistorychange__del_licencehistorychange__del_supporthis.py", line 79, in forwards
    ('new_value', self.gf('django.db.models.fields.TextField')(default=u'')),
  File "/home/ralph/local/lib/python2.7/site-packages/south/db/generic.py", line 44, in _cache_clear
    return func(self, table, *args, **opts)
  File "/home/ralph/local/lib/python2.7/site-packages/south/db/generic.py", line 352, in create_table
    ', '.join([col for col in columns if col]),
  File "/home/ralph/local/lib/python2.7/site-packages/south/db/generic.py", line 273, in execute
    cursor.execute(sql, params)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 114, in execute
    return self.cursor.execute(query, args)
  File "/home/ralph/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/home/ralph/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.DatabaseError: (1050, "Table 'ralph_assets_history' already exists")

**Comment by djbdjb00djb** [comment]
above the error information, in mysql run under command

mysql> DROP TABLE `ralph_assets_history` CASCADE;
mysql> ALTER TABLE `ralph_assets_asset` DROP COLUMN `service_id` CASCADE;
mysql> ALTER TABLE `ralph_assets_asset` DROP COLUMN `device_environment_id` CASCADE;

**Comment by mkurek** [comment]
assets migration should also be executed with `--fake` flag.

```
pip install ralph_assets ralph
ralph syncdb --all
ralph migrate --fake
```
