### ISSUE TITLE
makedemodata -i throws exception

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1389]
vagrant@precise64:~$ ralph make_demo_data  -i
Please select demo data (eg.: 1, 4, 6): 1
Traceback (most recent call last):
  File "/home/vagrant/bin/ralph", line 9, in <module>
    load_entry_point('ralph==2.2.0', 'console_scripts', 'ralph')()
  File "/home/vagrant/sources/ralph/src/ralph/**main**.py", line 56, in main
    execute_from_command_line(sys.argv)
  File "/home/vagrant/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/vagrant/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/home/vagrant/sources/ralph/src/ralph/util/management/commands/make_demo_data.py", line 60, in handle
    selected = self.select_demos()
  File "/home/vagrant/sources/ralph/src/ralph/util/management/commands/make_demo_data.py", line 83, in select_demos
    return [keys[idx] for idx in choices]
IndexError: list index out of range

**Comment by mkurek** [comment]
it's ralph2 bug.
