### ISSUE TITLE
ralph syncdb fails on Ubuntu 12.04 LTS Server

### ISSUE THREAD

**Issue by PirxDevs** [allegro/ralph#16]
Just wanted to give Ralph a try and installed fresh Ubuntu 12.04 LTS Server and then followed your installation instructions. Tried both pip and source one and both ways it fails on syncdb with following error:

(ralph)ralph@ralph:~$ ralph syncdb
Traceback (most recent call last):
  File "/home/ralph/bin/ralph", line 9, in <module>
    load_entry_point('ralph==1.0.1', 'console_scripts', 'ralph')()
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/**main**.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 231, in execute
    self.validate()
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 266, in validate
    num_errors = get_validation_errors(s, app)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/validation.py", line 30, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/loading.py", line 158, in get_app_errors
    self._populate()
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/loading.py", line 64, in _populate
    self.load_app(app_name, True)
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/loading.py", line 88, in load_app
    models = import_module('.models', app_name)
  File "/home/ralph/local/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/home/ralph/local/lib/python2.7/site-packages/ralph/account/models.py", line 161, in <module>
    for u in User.objects.order_by('id'):
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/query.py", line 875, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 817, in execute_sql
    cursor = self.connection.cursor()
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 306, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/home/ralph/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 387, in _cursor
    self.connection = Database.connect(**kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/home/ralph/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 187, in **init**
    super(Connection, self).**init**(_args, *_kwargs2)
TypeError: keywords must be strings

Not sure if its Ubuntu related or Ralph related problem. Just letting you know.

**Comment by PirxDevs** [comment]
Thanks for tip. DB created, but now I have two more issues:
1. When checking if evertyhing works running "ralph celeryd -l info" from project directory it fails with:

(ralph)ralph@ralph:~/project$ ralph celeryd -l info
/home/ralph/local/lib/python2.7/site-packages/djcelery/loaders.py:110: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
  warnings.warn("Using settings.DEBUG leads to a memory leak, never "
Traceback (most recent call last):
  File "/home/ralph/bin/ralph", line 9, in <module>
    load_entry_point('ralph==1.0.1', 'console_scripts', 'ralph')()
  File "/home/ralph/project/src/ralph/**main**.py", line 11, in main
    execute_from_command_line(sys.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 443, in execute_from_command_line
    utility.execute()
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 382, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ralph/local/lib/python2.7/site-packages/djcelery/management/base.py", line 74, in run_from_argv
    return super(CeleryCommand, self).run_from_argv(argv)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 196, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/home/ralph/local/lib/python2.7/site-packages/djcelery/management/base.py", line 67, in execute
    super(CeleryCommand, self).execute(_args, *_options)
  File "/home/ralph/local/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/home/ralph/local/lib/python2.7/site-packages/djcelery/management/commands/celeryd.py", line 25, in handle
    worker.run(_args, *_options)
  File "/home/ralph/local/lib/python2.7/site-packages/celery/bin/celeryd.py", line 155, in run
    return self.app.Worker(**kwargs).run()
  File "/home/ralph/local/lib/python2.7/site-packages/celery/apps/worker.py", line 161, in run
    print(str(self.colored.cyan(' \n', self.startup_info())) +
  File "/home/ralph/local/lib/python2.7/site-packages/celery/apps/worker.py", line 225, in startup_info
    'conninfo': self.app.connection().as_uri(),
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/connection.py", line 418, in as_uri
    fields = self.info()
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/connection.py", line 407, in info
    return OrderedDict(self._info())
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/connection.py", line 387, in _info
    D = self.transport.default_connection_params
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/connection.py", line 609, in transport
    self._transport = self.create_transport()
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/connection.py", line 369, in create_transport
    return self.get_transport_cls()(client=self)
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 609, in __init__
    self.connection_errors, self.channel_errors = self._get_errors()
  File "/home/ralph/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 640, in _get_errors
    from redis import exceptions
ImportError: No module named redis

But python-redis is installed in system (and was installed before Ralph installation).
1. When trying to acces ralph website it complains:

DatabaseError at /

(1146, "Table 'ralph.activitylog_ip' doesn't exist")

Request Method:     GET
Request URL:    http://ralph.exampe.com/
Django Version:     1.4
Exception Type:     DatabaseError
Exception Value:    

(1146, "Table 'ralph.activitylog_ip' doesn't exist")

Exception Location:     /home/ralph/lib/python2.7/site-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:  /usr/bin/python
Python Version:     2.7.3
Python Path:    

['/home/ralph/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/ralph/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/home/ralph/project/src',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/pymodules/python2.7',
 '/home/ralph/lib/python2.7/site-packages']
