### ISSUE TITLE
LDAP Sync not working

### ISSUE THREAD

**Issue by mholttech** [allegro/ralph#2298]
I am trying to set up LDAP sync with our 2008 AD server and am running into some issues.

Code inserted into src/ralph/settings/prod.py:

```
AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
AUTH_LDAP_SERVER_URI = "ldap://ladbsix.somenet.local:389"
AUTH_LDAP_BIND_DN = "CN=ralph,OU=Ralph,DC=somenet,DC=local"
AUTH_LDAP_BIND_PASSWORD = "somepass"
AUTH_LDAP_PROTOCOL_VERSION = 3
AUTH_LDAP_USER_USERNAME_ATTR = "sAMAccountName"
AUTH_LDAP_USER_SEARCH_BASE = "DC=allegrogroup,DC=internal"
AUTH_LDAP_USER_SEARCH_FILTER = '(&(objectClass=*)({0}=%(user)s))'.format(
  AUTH_LDAP_USER_USERNAME_ATTR)
AUTH_LDAP_USER_SEARCH = LDAPSearch(AUTH_LDAP_USER_SEARCH_BASE,
  ldap.SCOPE_SUBTREE, AUTH_LDAP_USER_SEARCH_FILTER)
AUTH_LDAP_USER_ATTR_MAP = {
  "first_name": "givenName",
  "last_name": "sn",
  "email": "mail",
}

from ralph.accounts.ldap import MappedGroupOfNamesType

AUTH_LDAP_GROUP_MAPPING = {
  'CN=_gr_ralph_admin,OU=Ralph,DC=somenet,DC=local': "staff",
  'CN=_gr_ralph_admin,OU=Ralph,DC=somenet,DC=local': "superuser",
  'CN=_gr_ralph_admin,OU=Ralph,DC=somenet,DC=local': "ladb",
}
AUTH_LDAP_MIRROR_GROUPS = True
AUTH_LDAP_GROUP_TYPE = MappedGroupOfNamesType(name_attr="cn")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("DC=somenet,DC=local",
    ldap.SCOPE_SUBTREE, '(objectClass=group)')

AUTH_LDAP_NESTED_GROUPS = {
    'CN=_gr_ralph_admin,OU=Ralph,DC=somenet,DC=local': "staff",  # _gr_ralph_users contains other LDAP groups inside
}

AUTH_LDAP_USER_FILTER = '(|(memberOf=CN=_gr_ralph_admin,OU=Ralph,'\
    'DC=somenet,DC=local))'
```

output from running `ralph ldap_sync`

```

Traceback (most recent call last):
  File "/usr/local/bin/ralph", line 9, in <module>
    load_entry_point('ralph==3.0.0', 'console_scripts', 'ralph')()
  File "/opt/ralph/src/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/src/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/ralph/src/ralph/accounts/management/commands/ldap_sync.py", line 219, in handle
    self.nested_groups = NestedGroups()
  File "/opt/ralph/src/ralph/accounts/management/commands/ldap_sync.py", line 103, in __init__
    self.group_users, self.users_groups = get_nested_groups()
TypeError: 'NoneType' object is not iterable
```

**Comment by mholttech** [comment]
I applied the patch and now i'm getting

```
ldap.OPERATIONS_ERROR: {'desc': 'Operations error', 'info': '000004DC: LdapErr: DSID-0C0906DD, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1772'}
```

I've double and triple checked and everything looks right based on the documentation and googling

**Comment by ghost** [comment]
Did you set correct password:
`AUTH_LDAP_BIND_PASSWORD = "somepass"`
?

**Comment by mholttech** [comment]
Yea I did and I have even reset the password to something else, password works to log in and the user is in the Domain Admins group in AD

**Comment by mkurek** [comment]
@mholttech Try to run this command first:

```
ldapsearch -h ladbsix.somenet.local -p 389 -w somepass -D "CN=ralph,OU=Ralph,DC=somenet,DC=local" -b "CN=_gr_ralph_admin,OU=Ralph,DC=somenet,DC=local"
```

This should check if your base settings (`AUTH_LDAP_BIND_PASSWORD`, `AUTH_LDAP_SERVER_URI`, `AUTH_LDAP_BIND_DN`) are valid. I'm not sure if your `AUTH_LDAP_BIND_DN` is properly set, but i'm not the ldap expert.

On the other hand, you have `AUTH_LDAP_USER_SEARCH_BASE = "DC=allegrogroup,DC=internal"`, which is probably wrong.

**Comment by mholttech** [comment]
I successfully ran `ldapsearch -h ladbsix -p 389 -x -D "cn=ralph,ou=Ralph,dc=ladbnet,dc=local" -b "dc=ladbnet,dc=local" -W` entered the password and got a response from the AD, but still no luck getting ralph to Bind.  

Here's what i've got right now in `src/ralph/settings/prod.py` which I copied straight from the doc mentioned earlier

```
AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
AUTH_LDAP_SERVER_URI = "ldap://ladbsix:389"
AUTH_LDAP_BIND_DN = "CN=Ralph,OU=Ralph,DC=ladbnet,DC=local"
AUTH_LDAP_BIND_PASSWORD = "somesecret"
AUTH_LDAP_PROTOCOL_VERSION = 3
AUTH_LDAP_USER_USERNAME_ATTR = "sAMAccountName"
AUTH_LDAP_USER_SEARCH_BASE = "DC=ladbnet,DC=local"
AUTH_LDAP_USER_SEARCH_FILTER = '(&(objectClass=*)({0}=%(user)s))'.format(
  AUTH_LDAP_USER_USERNAME_ATTR)
AUTH_LDAP_USER_SEARCH = LDAPSearch(AUTH_LDAP_USER_SEARCH_BASE,
  ldap.SCOPE_SUBTREE, AUTH_LDAP_USER_SEARCH_FILTER)
AUTH_LDAP_USER_ATTR_MAP = {
  "first_name": "givenName",
  "last_name": "sn",
  "email": "mail",
}

from ralph.accounts.ldap import MappedGroupOfNamesType
AUTH_LDAP_GROUP_MAPPING = {
  'CN=_gr_ralph_admin,OU=Ralph,DC=ladbnet,DC=local': "staff",
  'CN=_gr_ralph_admin,OU=Ralph,DC=ladbnet,DC=local': "superuser",
}
AUTH_LDAP_MIRROR_GROUPS = True
AUTH_LDAP_GROUP_TYPE = MappedGroupOfNamesType(name_attr="cn")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("DC=ladbnet,DC=local",
    ldap.SCOPE_SUBTREE, '(objectClass=group)')
```

and this is what i'm getting back from Ralph at this point:

```
Traceback (most recent call last):
  File "/usr/local/bin/ralph", line 9, in <module>
    load_entry_point('ralph==3.0.0', 'console_scripts', 'ralph')()
  File "/opt/ralph/src/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/src/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/ralph/src/ralph/accounts/management/commands/ldap_sync.py", line 224, in handle
    synced = self.populate_users()
  File "/opt/ralph/src/ralph/accounts/management/commands/ldap_sync.py", line 230, in populate_users
    for user_dn, ldap_dict in self._get_users():
  File "/opt/ralph/src/ralph/accounts/management/commands/ldap_sync.py", line 154, in _run_ldap_query
    r_type, r_data, r_msgid, serverctrls = conn.result3(msgid)
  File "/usr/local/lib/python3.4/dist-packages/ldap/ldapobject.py", line 680, in result3
    resp_ctrl_classes=resp_ctrl_classes
  File "/usr/local/lib/python3.4/dist-packages/ldap/ldapobject.py", line 687, in result4
    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)
  File "/usr/local/lib/python3.4/dist-packages/ldap/ldapobject.py", line 263, in _ldap_call
    result = func(*args,**kwargs)
ldap.OPERATIONS_ERROR: {'info': '000004DC: LdapErr: DSID-0C0906DD, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1772', 'desc': 'Operations error'}
```

**Comment by mholttech** [comment]
I am wondering if any progress has been made on this issue

**Comment by mkurek** [comment]
@mholttech i'm afraid that it's not our (Ralph's) issue, but rather your's LDAP server (or network configuration etc). It look's like you have everything properly configured - we're running our production Ralph on the same config (excluding ldap host and password of course) and everything is working fine. We have also messages (confirmations) from some other users of Ralph that LDAP is working for them as well.

**Comment by mholttech** [comment]
I just tested with the latest snapshot and i've got ldap_sync working however I can not log in with any of the users, appears to be the same issue as https://github.com/allegro/ralph/issues/2240 but I don't see a resolution there

**Comment by mkurek** [comment]
@mholttech - do you still have `django_auth_ldap.backend.LDAPBackend` in your `AUTHENTICATION_BACKENDS` (http://ralph-ng.readthedocs.io/en/ng/installation/#ldap-authentication) in settings?

**Comment by mholttech** [comment]
This is what i've got on the bottom of prod.py

```
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
AUTH_LDAP_SERVER_URI = "ldap://mydc.mydomain.local:389"
AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = False
AUTH_LDAP_BIND_DN = "CN=ralph,OU=No O365,OU=Users,OU=LADB,DC=mydomain,DC=local"
AUTH_LDAP_BIND_PASSWORD = "secretpassword!"
AUTH_LDAP_PROTOCOL_VERSION = 3
AUTH_LDAP_START_TLS = True

# User and group search objects and types

AUTH_LDAP_USER_USERNAME_ATTR = "userPrincipalName"
AUTH_LDAP_USER_SEARCH_BASE = "OU=Users,OU=LADB,DC=mydomain,DC=local"
AUTH_LDAP_USER_SEARCH_FILTER = '(&(objectclass=user)(objectcategory=person))'.format(
  AUTH_LDAP_USER_USERNAME_ATTR)
AUTH_LDAP_USER_SEARCH = LDAPSearch(AUTH_LDAP_USER_SEARCH_BASE,
  ldap.SCOPE_SUBTREE, AUTH_LDAP_USER_SEARCH_FILTER)
AUTH_LDAP_USER_FILTER = '(memberOf=CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local)'
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
    ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
)
AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()
AUTH_LDAP_REQUIRE_GROUP = "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local"
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
    "is_staff": "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
    "is_superuser": "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
}
AUTH_LDAP_PROFILE_FLAGS_BY_GROUP = {
    "is_active": "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
    "is_staff": "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
    "is_superuser": "CN=Ralph Users,OU=Security Groups,OU=Groups,OU=LADB,DC=mydomain,DC=local",
}

# What to do once the user is authenticated

AUTH_LDAP_USER_ATTR_MAP = {
  "first_name": "givenName",
  "last_name": "sn",
  "email": "userPrincipalName",
}

LOGGING['loggers']['django_auth_ldap'] = {
      'handlers': ['file'],
      'propagate': True,
      'level': 'DEBUG',
  }
```

**Comment by mholttech** [comment]
oops missed a bit, this is right above the import ldap

```
AUTHENTICATION_BACKENDS = (
      'django_auth_ldap.backend.LDAPBackend',
      'django.contrib.auth.backends.ModelBackend',
  )
```

**Comment by mkurek** [comment]
@mholttech Could you add the following logger to your settings:

```
LOGGING['loggers']['django_auth_ldap'] = {
    'level': 'DEBUG',
    'handlers': ['console', 'file']
}
```

Then you should see additional output in console and log file when logging. Could you paste it here?

**Comment by project0** [comment]
Nested group sync doesnt work for me, there is at minimum one issue with python3
The following line gets an byte char: 
https://github.com/allegro/ralph/blob/d871ef91fe01c57e3b3660fa5bed7ae2175d2720/src/ralph/accounts/ldap.py#L156 but in https://github.com/allegro/ralph/blob/d871ef91fe01c57e3b3660fa5bed7ae2175d2720/src/ralph/accounts/ldap.py#L169 is a string required. When fixed with string casting, i got index out of range errors.

**Comment by roteme13** [comment]
Hi, 
I'm having the same issue of not able to login with ldap user (ldap_sync worked).
The error I'm getting is:

"Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive."

although all the user flags are correct (is_staff, is_superuser,is_active).

Please advise

**Comment by mkurek** [comment]
@roteme13 could you paste here your `AUTH_*` settings?

**Comment by roteme13** [comment]
```
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

AUTHENTICATION_BACKENDS = ( 'django_auth_ldap.backend.LDAPBackend', 'django.contrib.auth.backends.ModelBackend',)

AUTH_LDAP_SERVER_URI = "ldap://dc.com:389"
AUTH_LDAP_BIND_DN = 'CN=ldap,OU=Service Accounts,DC=com'
AUTH_LDAP_BIND_PASSWORD = "1234567"

AUTH_LDAP_PROTOCOL_VERSION = 3
AUTH_LDAP_USER_USERNAME_ATTR = "sAMAccountName"
AUTH_LDAP_USER_SEARCH_BASE = "OU=Users,DC=com"
AUTH_LDAP_USER_SEARCH_FILTER = '(&(objectClass=*)({0}=%(user)s))'.format(AUTH_LDAP_USER_USERNAME_ATTR)
AUTH_LDAP_USER_SEARCH = LDAPSearch(AUTH_LDAP_USER_SEARCH_BASE,ldap.SCOPE_SUBTREE, AUTH_LDAP_USER_SEARCH_FILTER)
AUTH_LDAP_USER_ATTR_MAP = {
  "first_name": "givenName",
  "last_name": "sn",
  "email": "mail",
  "company": "company",
  "manager": "manager",
  "department": "department",
  "employee_id": "employeeID",
}

AUTH_LDAP_GROUP_TYPE = GroupOfNamesType(name_attr="cn")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("OU=Security Groups,OU=Groups,DC=com", ldap.SCOPE_SUBTREE, '(objectClass=group)')

AUTH_LDAP_USER_FLAGS_BY_GROUP = 
{"is_superuser": ['CN=IT Team,OU=Security Groups,OU=Groups,DC=com',
                             'CN=Infrastructure Team,OU=Security Groups,OU=Groups,DC=com',
                             'CN=Services Team,OU=Security Groups,OU=Groups,DC=com',
                             'CN=Control Team,OU=Security Groups,OU=Groups,DC=com',
                             'CN=Operations Team,OU=Security Groups,OU=Groups,DC=com',
                             'CN=Program Management Team,OU=Security Groups,OU=Groups,DC=com'],
 "is_staff": ['CN=IT Team,OU=Security Groups,OU=Groups,DC=com',
                   'CN=Control Team,OU=Security Groups,OU=Groups,DC=com',
                   'CN=Planning Team,OU=Security Groups,OU=Groups,DC=com',
                   'CN=Program Team,OU=Security Groups,OU=Groups,DC=com',
                   'CN=Infrastructure Team,OU=Security Groups,OU=Groups,DC=com',
                   'CN=Services Team,OU=Security Groups,OU=Groups,DC=com']}

AUTH_LDAP_USER_FILTER = '(|(memberOf=CN=IT Team,OU=Security Groups,OU=Groups,DC=com)(memberOf=CN=Planning Team,OU=Security Groups,OU=Groups,DC=com)(memberOf=CN=Infrastructure Team,OU=Security Groups,OU=Groups,DC=com)(memberOf=CN=Services Team,OU=Security Groups,OU=Groups,DC=com)(memberOf=CN=Program Team,OU=Security Groups,OU=Groups,DC=com)(memberOf=CN=Control Team,OU=Security Groups,OU=Groups,DC=com))'

PASSWORD_HASHERS = (
    'django_plainpasswordhasher.PlainPasswordHasher',
)
```

That's it.
Thanks

**Comment by roteme13** [comment]
@mkurek , I tried to physically update my ldap synced user's password in the database (to the local superuser hashed password) and successfully connected. Could the issue be related to password hashing?

**Comment by mkurek** [comment]
@roteme13 what to you mean by "successfully connected"? That you've successfully logged into ralph? If yes, issue is still the same - because of the following configuration of authentication backends:

```
AUTHENTICATION_BACKENDS = ( 
  'django_auth_ldap.backend.LDAPBackend', 
  'django.contrib.auth.backends.ModelBackend',
)
```

Django will first try to authenticate you through `LDAPBackend` and, if it fails, try to authenticate you through `ModelBackend` - since your password in DB match the password you passed in the login form, you've successfully logged-in using `ModelBackend`.

The question is why `LDAPBackend` is not working correctly. Please try to set logging for django_auth_ldap and see if there is anything "suspicious" there:
```
LOGGING['loggers']['django_auth_ldap'] = {
    'level': 'DEBUG',
    'handlers': ['console', 'file']
}
```

**Comment by roteme13** [comment]
@mkurek, I added the logging and nothing happens when I try to authenticate, just when running ldap_sync. 
I also tried running tcpdump on every interface involved in the process and it didn't show any packets to the domain controller. 
It seems like the LDAPBackend is entirely not in use.

**Comment by roteme13** [comment]
@mkurek, Any news regarding this issue?

**Comment by rauf547** [comment]
Hi,
I'm also having the same issue of not able to login with ldap user (ldap_sync worked) in ralph3. Any news of this issue?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
