### ISSUE TITLE
Cannot import data center assets or IP addresses

### ISSUE THREAD

**Issue by gatvo** [allegro/ralph#2667]
Hello,

I'm trying to import data center assets on ralph from a file (any of the valid formats), but whenever I do, I get an error such as this:

```
Line number: 1 - save() prohibited to prevent data loss due to unsaved related object 'base_object'.
OrderedDict([('parent', ''), ('parent_str', ''), ('service_env', ''), ('service_env_str', ''), ('management_ip', '171.235.226.999'), ('rack', ''), ('rack_str', ''), ('budget_info', ''), ('budget_info_str', ''), ('model', 16.0), ('model_str', '[Blade System] Asus DL380'), ('id', ''), ('created', '2016-06-02 12:00:00'), ('modified', '2016-06-02 12:00:00'), ('remarks', ''), ('configuration_path', ''), ('configuration_path_str', ''), ('hostname', 'ralph999.allegro.pl'), ('sn', '018-05-9672'), ('barcode', '39920942'), ('niw', ''), ('required_support', '0'), ('order_no', ''), ('invoice_no', ''), ('invoice_date', ''), ('price', ''), ('provider', ''), ('depreciation_rate', '25.00'), ('force_depreciation', '0'), ('depreciation_end_date', ''), ('task_url', ''), ('property_of', 1.0), ('property_of_str', 'Grupa Allegro SP. z o.o.'), ('status', 1.0), ('position', ''), ('orientation', 1.0), ('slot_no', ''), ('firmware_version', ''), ('bios_version', ''), ('source', 2.0), ('delivery_date', ''), ('production_year', ''), ('production_use_date', ''), ('tags', ''), ('tags_str', '')])
Traceback (most recent call last):
File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 42, in _get_or_create_management_ip
ip = IPAddress.objects.get(address=address)
File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 127, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
ralph.networks.models.networks.DoesNotExist: IPAddress matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 374, in import_data
self.import_obj(instance, row, real_dry_run)
File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 238, in import_obj
self.import_field(field, obj, data)
ValueError: save() prohibited to prevent data loss due to unsaved related object 'base_object'.
```

I thought I first needed to add the IP addresses, but upon trying to do that I get the following error:

```
Line number: 1 - __str__ returned non-string (type NoneType)
OrderedDict([('asset ', ''), (' network ', ''), (' created ', ''), (' modified ', ''), (' last_seen ', ''), (' ethernet ', ''), (' address ', '1.113.6.25'), (' hostname ', 'this.is.a.test.host.name'), (' number ', ''), (' is_management ', '1'), (' is_public ', '1'), (' is_gateway ', '0'), (' status ', ''), (' dhcp_expose', ''), ('id', '')])
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 381, in import_data
row_result.object_repr = force_text(instance)
File "/usr/local/lib/python3.4/dist-packages/django/utils/encoding.py", line 90, in force_text
s = six.text_type(s)
TypeError: __str__ returned non-string (type NoneType)
```

**Comment by gatvo** [comment]
This might be able to help:
http://stackoverflow.com/a/33850878/4876466

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
