### ISSUE TITLE
Mac os  devlope env config error 

### ISSUE THREAD

**Issue by heidsoft** [allegro/ralph#2749]
```
System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1128a3f28>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check_migrations()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 168, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 321, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/loader.py", line 317, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration networks.0004_auto_20160606_1512 dependencies reference nonexistent parent node ('assets', '0012_auto_20160606_1409')
```

**Comment by mkurek** [comment]
Hi @heidsoft . What command did you run? How did you installed Ralph and what version are you using?

**Comment by heidsoft** [comment]
i am git clone master , run /Users/heidsoft/work/ralph/src/ralph/cross_validator/**main**.py migrate

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
