### ISSUE TITLE
ralph impossible to install (errno: 150)

### ISSUE THREAD

**Issue by gerickt** [allegro/ralph#2799]
```
root@dcim:~$ ralph migrate
Operations to perform:
  Synchronize unmigrated apps: dc_view, ralph2_sync, mptt, messages, ralph_admin, table, humanize, import_export, taggit_serializer, django_rq, permissions, staticfiles, rest_framework, foundation
  Apply all migrations: security, deployment, taggit, assets, transitions, admin, reports, custom_fields, accounts, supports, licences, reversion, virtual, data_center, sitetree, back_office, data_importer, operations, contenttypes, sessions, authtoken, auth, dhcp, external_services, networks, dashboards, attachments, domains
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20151204_0758... OK
  Applying accounts.0003_region_country... OK
  Applying accounts.0004_region_stocktaking_enabled... OK
  Applying admin.0001_initial... OK
  Applying data_importer.0001_initial... OK
  Applying data_importer.0002_auto_20151125_1354... OK
  Applying data_importer.0003_auto_20160624_1217... OK
  Applying data_importer.0004_auto_20160728_1046... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying assets.0001_initial... OK
  Applying assets.0002_auto_20151125_1354... OK
  Applying assets.0003_auto_20151126_2205... OK
  Applying assets.0004_auto_20151204_0758... OK
  Applying assets.0005_category_depreciation_rate... OK
  Applying assets.0006_category_show_buyout_date... OK
  Applying assets.0007_auto_20160122_1022... OK
  Applying assets.0008_auto_20160122_1429... OK
  Applying assets.0009_auto_20160307_1138... OK
  Applying assets.0010_auto_20160405_1531... OK
  Applying assets.0011_auto_20160603_0742... OK
  Applying assets.0012_auto_20160606_1409... OK
  Applying assets.0013_auto_20160615_2140... OK
  Applying assets.0014_memory... OK
  Applying assets.0015_auto_20160701_0952... OK
  Applying assets.0016_fibrechannelcard... OK
  Applying assets.0017_processor... OK
  Applying assets.0018_disk... OK
  Applying assets.0019_auto_20160719_1443... OK
  Applying assets.0020_auto_20160803_0712...Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 220, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 209, in execute
    r = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 371, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 335, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1025, "Error on rename of './ralph/#sql-3c8_98' to './ralph/assets_configurationclass' (errno: 150)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/bin/ralph", line 9, in <module>
    load_entry_point('ralph==3.0.0', 'console_scripts', 'ralph')()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 222, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/migrations/executor.py", line 110, in migrate
    self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/migrations/executor.py", line 148, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/migrations/migration.py", line 115, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/migrations/operations/special.py", line 43, in database_forwards
    database_operation.database_forwards(app_label, schema_editor, from_state, to_state)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/migrations/operations/fields.py", line 275, in database_forwards
    to_model._meta.get_field(self.new_name),
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 547, in _alter_field
    self.execute(self._rename_field_sql(model._meta.db_table, old_field, new_field, new_type))
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 220, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 209, in execute
    r = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 371, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/cursors.py", line 335, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1025, "Error on rename of './ralph/#sql-3c8_98' to './ralph/assets_configurationclass' (errno: 150)")
```

**Comment by gerickt** [comment]
version is latest... i try another version 7080, 7076 and 7074... same problem too

**Comment by yiyuandao** [comment]
I got the same problem too.
And downgrade to ralph-core_3.0.0-snapshot-20160805-6680, then works well.
It seems that the latest version have problems.

**Comment by mkurek** [comment]
@gerickt @yiyuandao please refer to https://github.com/allegro/ralph/issues/2769 - we'll continue to fix this bug there.
