### ISSUE TITLE
Can not import Data center assets from xls file

### ISSUE THREAD

**Issue by yangliping** [allegro/ralph#2864]
I think it's related to the management_ip field. If I put an IP in it, it will raise following error:

![screen shot 2016-11-17 at 5 42 17 pm](https://cloud.githubusercontent.com/assets/6970919/20384205/f29cb6fa-aced-11e6-9dc9-89651448b0bc.png)

ERROR:root:save() prohibited to prevent data loss due to unsaved related object 'base_object'.
Traceback (most recent call last):
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 42, in _get_or_create_management_ip
    ip = IPAddress.objects.get(address=address)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
ralph.networks.models.networks.DoesNotExist: IPAddress matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 374, in import_data
    self.import_obj(instance, row, real_dry_run)
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 238, in import_obj
    self.import_field(field, obj, data)
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 230, in import_field
    field.save(obj, data)
  File "/usr/local/lib/python3.4/dist-packages/import_export/fields.py", line 108, in save
    setattr(obj, attrs[-1], self.clean(data))
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 82, in management_ip
    # IP entry to not try to change it's value
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 44, in _get_or_create_management_ip
    ip = _create_new_ip()
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 34, in _create_new_ip
    eth = self.ethernet_set.create()
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/related.py", line 756, in create
    return super(RelatedManager, self.db_manager(db)).create(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 685, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'base_object'.

If I leave the management_ip field empty, the following error will raise:

![screen shot 2016-11-17 at 5 39 19 pm](https://cloud.githubusercontent.com/assets/6970919/20384204/f29c0b10-aced-11e6-814c-1212ec871380.png)
  
ERROR:root:save() prohibited to prevent data loss due to unsaved related object 'base_object'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 374, in import_data
    self.import_obj(instance, row, real_dry_run)
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 238, in import_obj
    self.import_field(field, obj, data)
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 230, in import_field
    field.save(obj, data)
  File "/usr/local/lib/python3.4/dist-packages/import_export/fields.py", line 108, in save
    setattr(obj, attrs[-1], self.clean(data))
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 82, in management_ip
    # IP entry to not try to change it's value
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 65, in _get_or_create_management_ip
    ip.ethernet = self.ethernet_set.create()
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 34, in _create_new_ip
    eth = self.ethernet_set.create()
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/related.py", line 756, in create
    return super(RelatedManager, self.db_manager(db)).create(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 685, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'base_object'.
[17/Nov/2016 22:33:46] "POST /data_center/datacenterasset/import/ HTTP/1.1" 200 19993

Why? And how should I fix it?

**Comment by vi4m** [comment]
@xliiv ?

**Comment by ghost** [comment]
@yangliping make sure that IPs (and other objects related to Asset) mentioned in your import xls file do exist in db. Can you confirm that?
Beside the above, a minimal problematic file would be very helpful to debug/write regression test.
Could you attach one?

**Comment by yangliping** [comment]
@xliiv The IP do not exist in db. But if you add the IP ahead, there will be another error. And the error is also relative to IP. Github does not support uploading xls files, so I save the file as xlsx and attached below.

![screen shot 2016-11-18 at 10 50 59 am](https://cloud.githubusercontent.com/assets/6970919/20416992/4c3b1f96-ad7d-11e6-9c5a-4f83d1fd2de7.png)

ERROR:root:save() prohibited to prevent data loss due to unsaved related object 'base_object'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 374, in import_data
    self.import_obj(instance, row, real_dry_run)
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 238, in import_obj
    self.import_field(field, obj, data)
  File "/usr/local/lib/python3.4/dist-packages/import_export/resources.py", line 230, in import_field
    field.save(obj, data)
  File "/usr/local/lib/python3.4/dist-packages/import_export/fields.py", line 108, in save
    setattr(obj, attrs[-1], self.clean(data))
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 82, in management_ip
    ip = self._get_or_create_management_ip(value)
  File "/opt/ralph/src/ralph/data_center/models/mixins.py", line 62, in _get_or_create_management_ip
    ip.ethernet = self.ethernet_set.create()
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/fields/related.py", line 756, in create
    return super(RelatedManager, self.db_manager(db)).create(*_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(_args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/base.py", line 685, in save
    "unsaved related object '%s'." % field.name
ValueError: save() prohibited to prevent data loss due to unsaved related object 'base_object'.

![screen shot 2016-11-18 at 10 54 16 am](https://cloud.githubusercontent.com/assets/6970919/20417027/927b1a56-ad7d-11e6-876c-fee03b6b58f5.png)

[DataCenterAsset-2016-11-17.xlsx](https://github.com/allegro/ralph/files/598968/DataCenterAsset-2016-11-17.xlsx)

**Comment by yangliping** [comment]
What's the best practice of debugging alpha inside the container? I'm now using the image from docker hub. 

https://hub.docker.com/r/allegrogroup/ralph/

**Comment by ghost** [comment]
@yangliping ok i got the error, I'll do the fix, hold on :)

ad. "docker debugging" if you have working docker container you can do

```
docker up run -it <container-id> bash
```

to go into working container. The rest should be the same as usual except it's docker image ;)

**Comment by ghost** [comment]
Here's the fix:
https://github.com/allegro/ralph/pull/2873

**Comment by yangliping** [comment]
@xliiv I've tested the fix. It works great. Thank you.
