### ISSUE TITLE
Some problem when making installation.

### ISSUE THREAD

**Issue by Jungle93** [allegro/ralph#3032]
Enviroment :
ralph-ng (2017-04-22 13:05:51)
ubuntu 14.04.05
python2.7 python3.4
mysql-server5.5
redies-server2.8.4

builtins.TypeError
TypeError: process() takes 2 positional arguments but 3 were given
Traceback (most recent call last)
File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
response = self.get_response(request)
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 233, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.4/dist-packages/six.py", line 686, in reraise
raise value
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 223, in get_response
response = middleware_method(request, response)
File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/middleware.py", line 129, in process_response
panel.generate_stats(request, response)
File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/panel.py", line 192, in generate_stats
query['sql'] = reformat_sql(query['sql'])
File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/utils.py", line 27, in reformat_sql
return swap_fields(''.join(stack.run(sql)))
File "/usr/local/lib/python3.4/dist-packages/sqlparse/engine/__init__.py", line 44, in run
stream = filter_.process(self, stream)
TypeError: process() takes 2 positional arguments but 3 were given

127.0.0.1 - - [22/Apr/2017 06:50:28] "GET /login/?next=/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 233, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/middleware.py", line 129, in process_response
    panel.generate_stats(request, response)
  File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/panel.py", line 192, in generate_stats
    query['sql'] = reformat_sql(query['sql'])
  File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/utils.py", line 27, in reformat_sql
    return swap_fields(''.join(stack.run(sql)))
  File "/usr/local/lib/python3.4/dist-packages/sqlparse/engine/__init__.py", line 44, in run
    stream = filter_.process(self, stream)
TypeError: process() takes 2 positional arguments but 3 were given

**Comment by Jungle93** [comment]
fix by update requirements/base.txt ====>
modify======> sqlparse==0.2.3

**Comment by rcsheets** [comment]
I just ran into this same exception the first time I tried to load the login page when launching ralph with `make run` from the standard Vagrant environment. Upgrading `sqlparse` to 0.2.3 seems to have resolved the issue.
