### ISSUE TITLE
when make menu, Permission `accounts.can_view_extra_serverroomview` does not exist

### ISSUE THREAD

**Issue by Jungle93** [allegro/ralph#3052]
ralph sitetree_resync_apps
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/sitetree/utils.py", line 102, in item
    perm = Permission.objects.get(codename=codename, content_type__app_label=app)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ralph", line 9, in <module>
    load_entry_point('ralph==3.0.0', 'console_scripts', 'ralph')()
  File "/home/jungle/PycharmProjects/ralph/src/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/home/jungle/PycharmProjects/ralph/src/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/sitetree/management/commands/sitetree_resync_apps.py", line 37, in handle
    tree_modules = import_project_sitetree_modules()
  File "/usr/local/lib/python3.4/dist-packages/sitetree/utils.py", line 151, in import_project_sitetree_modules
    module = import_app_sitetree_module(app)
  File "/usr/local/lib/python3.4/dist-packages/sitetree/utils.py", line 134, in import_app_sitetree_module
    sub_module = import_module('%s.%s' % (app, module_name))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/jungle/PycharmProjects/ralph/src/ralph/admin/sitetrees.py", line 101, in <module>
    access_by_perms='accounts.can_view_extra_serverroomview'
  File "/home/jungle/PycharmProjects/ralph/src/ralph/admin/sitetrees.py", line 39, in ralph_item
    return item(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/sitetree/utils.py", line 104, in item
    raise ValueError('Permission `%s.%s` does not exist.' % (app, codename))
ValueError: Permission `accounts.can_view_extra_serverroomview` does not exist.
make: *** [menu] Error 1

**Comment by Jungle93** [comment]
It has been two weeks from i stuck in this project.what a shit someone make!!!

**Comment by ar4s** [comment]
@Jungle93  please try run ``ralph migrate`` before ``ralph sitetree_resync_apps``.
``ralph migrate`` should create missing permission.

**Comment by Jungle93** [comment]
@ar4s 
jungle@ubuntu:~/PycharmProjects/ralph$ ralph migrate
Operations to perform:
  Synchronize unmigrated apps: django_rq, notifications, import_export, ralph_admin, foundation, taggit_serializer, rest_framework, messages, table, dc_view, humanize, mptt, staticfiles, permissions
  Apply all migrations: sessions, networks, data_importer, dashboards, deployment, domains, authtoken, auth, taggit, custom_fields, back_office, reversion, accounts, operations, sitetree, virtual, external_services, assets, licences, attachments, contenttypes, data_center, dhcp, admin, security, reports, transitions, supports
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.

I've tried that way for many times ,I've tried reinstall my env.

**Comment by Jungle93** [comment]
@ar4s 
sorry it is my fault ,
I should try the second way to install 
the  command line -->ralph migrate
does't work 
-->ralph-dev migrate work
so does
-->ralph-dev sitetree_resync_apps work
but why ?is there any setting of my enviroment wrong?

**Comment by Jungle93** [comment]
@ar4s By the way thank you for your help.

**Comment by vi4m** [comment]
Can you join our gitter channel? https://gitter.im/allegro/ralph It's something wrong with your installation, we have to get more details.

**Comment by vi4m** [comment]
Everything works now? Can we close this?
