### ISSUE TITLE
error post install package ralph-core 3.0.0-snapshot-20170901-8287 amd64

### ISSUE THREAD

**Issue by itboxltda** [allegro/ralph#3154]
S.O: ubuntu 14.04.1
ralph: ralph-core/wheezy,now 3.0.0-snapshot-20170901-8287 amd64

error:
```
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/bin/ralph", line 11, in <module>
    load_entry_point('ralph==3.0.0', 'console_scripts', 'ralph')()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/opt/ralph/ralph-core/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/notifications/apps.py", line 5, in <module>
    from ralph.notifications.sender import send_notification_for_model
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/notifications/sender.py", line 10, in <module>
    from ralph.lib.metrics import statsd
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/lib/metrics/__init__.py", line 1, in <module>
    from .collector import build_statsd_client, statsd
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/lib/metrics/collector.py", line 5, in <module>
    from statsd import defaults, StatsClient
ImportError: No module named 'statsd'
```

**Comment by vi4m** [comment]
We're working on it. 
In meantime, you can revert to older versions with apt-get

**Comment by vi4m** [comment]
I've removed broken builds (~ 7 days ago) and paused cron jobs, so it should be possible to downgrade

**Comment by itboxltda** [comment]
the fixed error is:

```
pip install statsd
```

this way install statsd 3.2.1

**Comment by vi4m** [comment]
statsd should be optional #3155 - work here
