### ISSUE TITLE
recipe for target 'menu' failed

### ISSUE THREAD

**Issue by pjanzen** [allegro/ralph#3258]
Hi,

I have setup a vagrant dev enviroment and that works fine initially. If I do a 'vagrant halt' and 'vagrant up' and login to the box I am unable to start ralph3.

The error I am getting is this:

```
(venv) vagrant@ralph-dev:~/ralph$ make menu
ralph sitetree_resync_apps
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/ralph", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/vagrant/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/home/vagrant/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/vagrant/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/vagrant/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/vagrant/venv/lib/python3.5/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ralph' distribution was not found and is required by the application
Makefile:58: recipe for target 'menu' failed
make: *** [menu] Error 1
```

I am getting the same error when I run 'make run' I am unsure how to continue.

**Comment by Chez** [comment]
I'm getting the same error. I had to remove the virtualbox and start from the beginning.

**Comment by Chez** [comment]
Is there any chance of getting some feedback by support for this issue?

**Comment by djagoo** [comment]
Ran into the same issue today. It's working fine after vagrant up but after the first vagrant reload the error is showing up.

**Comment by Chez** [comment]
djagoo, hope you get better response than we have thus far...

**Comment by vi4m** [comment]
@MarekBleschke can we reproduce it?

**Comment by m1kra** [comment]
I had a similar issue and running `vagrant up --provision` helped. Still, the flag `--provision` should only be needed once.

EDIT:
It seems that after `vagrant halt` and `vagrant up` some files are deleted. Another work around is to copy `/home/vagrant/ralph/` from guest to `ralph` direcotry on hypervisor, after first `vagrant up`. Then, when doing `vagrant up` or `vagrant rsync`, those directories won't be overwritten.
