### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding

### ISSUE THREAD

**Issue by ElliotLepley** [allegro/ralph#3348]
Hey there, on attempt to initially run ralph migrate, a python error regarding importing a module fails. Any idea on how to resolve this on a clean install of Ubuntu 16.04?

`ralph migrate`
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted (core dumped)

export DATABASE_NAME=ralph
export DATABASE_USER=ralphuser
export DATABASE_PASSWORD=somepassword
export DATABASE_HOST=localhost
export PATH=/opt/ralph/ralph-core/bin/:$PATH
export RALPH_DEBUG=1

`echo $PYTHONHOME`
/opt/ralph/ralph-core/lib

**Comment by vi4m** [comment]
It seems like python version mismatch... Can you install it on clean ubuntu14.04 system?

**Comment by ElliotLepley** [comment]
Hey vi4m, upon installing into a clean Ubuntu14.04 VM (GCP), I've got it to a different error now regarding statsd:

`Traceback (most recent call last):
  File "/opt/ralph/ralph-core/bin/ralph", line 11, in <module>
    sys.exit(prod())
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute
_from_command_line
    utility.execute()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/apps/config.py", line 112, in create
    mod = import_module(mod_path)
  File "/opt/ralph/ralph-core/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/notifications/apps.py", line 5, in <module>
    from ralph.notifications.sender import send_notification_for_model
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/notifications/sender.py", line 10, in <module>
    from ralph.lib.metrics import statsd
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/lib/metrics/__init__.py", line 1, in <module>
    from .collector import build_statsd_client, statsd
  File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/lib/metrics/collector.py", line 5, in <module>
    from statsd import defaults, StatsClient
ImportError: No module named 'statsd'`

**Comment by ElliotLepley** [comment]
`pip install statsd` resolved this.

**Comment by vi4m** [comment]
Yes, `pip install` solves the issue. We've fixed this in upcoming release scheduled till the end of December.

**Comment by niteshsinghal88** [comment]
Hello, I am getting the similar issue:

![error1](https://user-images.githubusercontent.com/31091290/94838669-89ff8680-0433-11eb-857e-5ccf73351cbf.JPG)
![error2](https://user-images.githubusercontent.com/31091290/94838689-91bf2b00-0433-11eb-9ce2-c62559948fc4.JPG)

```
-hdp ~]$ /opt/anaconda3/bin/jupyter notebook
.......
[I 11:40:05.457 NotebookApp] The Jupyter Notebook is running at: http://usdfwxx.com:8888/
..........
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007f55e7053740 (most recent call first):
ls: cannot access /usr/hdp//hadoop/lib: No such file or directory
......
ExitCodeException exitCode=134: Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007f45a6104740 (most recent call first):
```

I already tried following but didn't help:

1. exporting environment variables in my user's bash profile.
2. tried updating Py4j version to py4j-0.10.9-src.zip in '/usr/hdp/current/spark2-client//python/lib'
3. updating python version to 3.6 and then 3.7 and pointing '/opt/anaconda3/bin/python3 -> /usr/local/bin/python3.7'
and /opt/anaconda3/bin/python3 -> python3.5

4. 
pip install findspark
pip install statsd
python3 -m pip install pyspark

Need your expert advise on this now.
