### ISSUE TITLE
'sudo ralphctl migrate' failed with Ubuntu 18.04

### ISSUE THREAD

**Issue by h133gqa** [allegro/ralph#3361]
Hello, 

I got a problem with a fresh install of Ralph. 

System Environment:
Ubuntu 18.04.01 LTS latest patch.
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64)

Installed ralph-core with Repo on instructions by [https://ralph-ng.readthedocs.io/en/latest/installation/installation/](https://ralph-ng.readthedocs.io/en/latest/installation/installation/)

    sudo apt-key adv --keyserver  hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
    sudo sh -c "echo 'deb https://dl.bintray.com/vi4m/ralph bionic main' >  /etc/apt/sources.list.d/vi4m_ralph.list"
    sudo apt-get update
    sudo apt-get install mysql-server nginx ralph-core

**When I try to run `sudo ralphctl migrate` from this part**

    echo "create database ralph_ng" | sudo mysql
    echo "create user 'ralph_ng'@'localhost' identified by 'ralph_ng'" | sudo mysql
    echo "grant all privileges on ralph_ng.* to 'ralph_ng'@'localhost'" | sudo mysql
    sudo ralphctl migrate
    sudo ralphctl createsuperuser`

**I get this:**

`Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/bin/ralph", line 11, in <module>
    sys.exit(prod())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/__main__.py", line 29, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/base.py", line 444, in execute
    self.check()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/base.py", line 482, in check
    include_deployment_checks=include_deployment_checks,
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 1205, in check
    errors.extend(cls._check_fields(**kwargs))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 1282, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 934, in check
    errors = super(AutoField, self).check(**kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 207, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 306, in _check_backend_specific_checks
    return connection.validation.check_field(self, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 18, in check_field
    field_type = field.db_type(connection)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 614, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/__init__.py", line 36, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 196, in data_types
    if self.features.supports_microsecond_precision:
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/features.py", line 52, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4) and Database.version_info >= (1, 2, 5)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/functional.py", line 59, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 371, in mysql_version
    with self.temporary_connection():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 462, in temporary_connection
    cursor = self.cursor()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 164, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 135, in _cursor
    self.ensure_connection()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")`

Manual connection with mysql -u ralph_ng -p and the set password works, the config /etc/ralph/conf.d/database.conf is correct. 

Any Ideas? maybe the mysql version?

**Comment by szymi-** [comment]
Try creating the database and user like this (you might need to first delete the old user):

    echo "create database ralph_ng" | sudo mysql
    echo "create user 'ralph_ng'@'127.0.0.1' identified by 'ralph_ng'" | sudo mysql
    echo "grant all privileges on ralph_ng.* to 'ralph_ng'@'127.0.0.1'" | sudo mysql

Let me know if it works, then I will fix the documentation.

**Comment by h133gqa** [comment]
Hi, yes it worked, but only because I used the simple password 'ralph_ng' with complex (other) password it does not work out. 

the scripts went through correctly, but now I get this in the log and error 500:
`[03.01.2019 10:15:34,293] WARNING [MainProcess 8533] base - Not Found: /favicon.ico
[03.01.2019 10:17:29,790] WARNING [MainProcess 1552] collector - Statsd not installed or configured - metrics will NOT be collected
[03.01.2019 10:17:29,790] WARNING [MainProcess 1551] collector - Statsd not installed or configured - metrics will NOT be collected
[03.01.2019 10:18:02,646] ERROR   [MainProcess 1552] base - Internal Server Error: /
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 51, in inner
    with self._recreate_cm():
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/transaction.py", line 150, in __enter__
    if not connection.get_autocommit():
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 286, in get_autocommit
    self.ensure_connection()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")
[03.01.2019 10:18:04,925] ERROR   [MainProcess 1552] base - Internal Server Error: /
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 51, in inner
    with self._recreate_cm():
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/transaction.py", line 150, in __enter__
    if not connection.get_autocommit():
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 286, in get_autocommit
    self.ensure_connection()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 130, in ensure_connection
    self.connect()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/transaction_hooks/mixin.py", line 75, in connect
    super(TransactionHooksDatabaseWrapperMixin, self).connect(*a, **kw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/base/base.py", line 119, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 276, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")`

**Comment by h133gqa** [comment]
I deleted the sql user again and created it new. I removed the login restriction location (%). 
Now it worked out.

**Comment by szymi-** [comment]
Thanks for your input, it will help us improve the documentation and the package. I think with the database password there are two problems here. First one appears to be on our side, i.e. the password in the /etc/ralph/conf.d/database.conf should be enclosed in quotation marks. I will fix that. The second one is bash related. I think creating the user in mysql shell instead of echoing mysql commands and piping them to mysql should solve the problem. I will update the documentation not to cause confusion.
