### ISSUE TITLE
Mariadb maximum keylength 767

### ISSUE THREAD

**Issue by tsdogs** [allegro/ralph#3398]
### Steps to reproduce
Install on Ubuntu 18.04 with mariadb-server

### Expected behavior

ralphctl migrate complete successfully

### Actual behavior

Exception raised
Applying accounts.0001_initial...Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')
### Environment

* Ralph version:  ralph-core              20190124.2       amd64
* Mariadb: mariadb-server          1:10.1.34-0ubunt all
* Operating system: Ubuntu 18.04
* Method of installation: repository package (as per installation documentation)

**Comment by vi4m** [comment]
This is weird. @romcheg

**Comment by romcheg** [comment]
We do not test Ralph with MariaDB atm. You are welcome to start a topic at  Ralph forum: https://ralph.discourse.group

**Comment by CaptainSifff** [comment]
You can try my branch over here:
https://github.com/allegro/ralph/pull/3405
I updated the pipeline for mariadb and did not encounter any errors.

**Comment by romcheg** [comment]
Re-opening the issue since thanks to @CaptainSifff mariadb is back on the table. @tsdogs could you please check the issue still persists for you?

**Comment by tsdogs** [comment]
I'll have a try this weekend and report back.

**Comment by tsdogs** [comment]
I have tried setup an environment to build ralph, but either documentation is old or I'm not able to even start the vagrant environment.
If you can provide a prebuilt package that would be best, otherwise point me on how to setup build environment.

**Comment by tsdogs** [comment]
ok,never mind. docker is now building.

**Comment by romcheg** [comment]
@tsdogs vagrant support was deprecated and removed. The documentation will be automatically rebuilt as soon as we tag a release. Please make sure you have the latest sources since there should not be a vagrant catalogue there.

**Comment by romcheg** [comment]
Also you don’t have to build docker images, the latest release is available on dockerhub as  allegro/ralph and allegro/ralph-static-nginx

**Comment by tsdogs** [comment]
I've built the ng tree from @CaptainSifff installed on a 18.04 ubuntu but the "ralphctl migrate" still gives the same error: 

Applying accounts.0001_initial...Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1071, 'Specified key was too long; max key length is 767 bytes')

**Comment by tsdogs** [comment]
Hello,
I found the source of this error. It is related to the default collate of mariadb. 
Creating the database with utf8 (as stated in the documentation) solved the problem (my bad).

CREATE database ralph default character set 'utf8';

**Comment by romcheg** [comment]
@tsdogs many users are hit by this issue. I will mention the solution in the documentation, perhaps. I'm normally trying to avoid documenting 3rd party systems but for this specific issue it's better to make an exceptions.

**Comment by tsdogs** [comment]
@romcheg I think the issue is that in the documentation in the bionic and newer section there is no mention of the create database (there's only the part for the user creation).
So I went by default with a simple "create database ralph_ng;" with default charset.

Probably adding the create database example would be enough.
