### ISSUE TITLE
500 error on Dashboard if i have loan in progress

### ISSUE THREAD

**Issue by dennisjmi24** [allegro/ralph#3473]
Hey i tested it with my admin user

if i am the user of a device in back office assets and the device has status loan in progress then i get a error 500 message on my Dashboard

log
`[16.07.2019 13:01:41,968] ERROR   [MainProcess 26801] base - Internal Server Error: /
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 202, in _render
    return self.nodelist.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 919, in render_node
    return node.render(context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/template/base.py", line 1273, in render
    _dict = func(*resolved_args, **resolved_kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/admin/templatetags/dashboard_tags.py", line 182, in ralph_summary
    accept_for_loan_tile_data = get_user_equipment_to_accept_loan_tile_data(user=user)  # noqa
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/admin/templatetags/dashboard_tags.py", line 65, in get_user_equipment_to_accept_loan_tile_data
    'url': get_loan_acceptance_url(user),
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/accounts/helpers.py", line 70, in get_loan_acceptance_url
    url = reverse(url_name, args=(ACCEPTANCE_LOAN_TRANSITION_ID,))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
django.core.urlresolvers.NoReverseMatch: Reverse for 'back_office_backofficeasset_transition_bulk' with arguments '(None,)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['back_office/backofficeasset/transition/(?P<transition_pk>\\d+)$']`

### Expected behavior
you should see the dashboard

### Actual behavior
you can't access the dashboard anymore because of this 500 error

### Environment
* Ralph version: 20190627.1
* Operating system: Ubuntu 18.04.2 LTS
* Method of installation: Deb package

**Comment by dennisjmi24** [comment]
if i  change the status from my device to another like "in use" then the error message is gone
