### ISSUE TITLE
problem installing ralph - gulp

### ISSUE THREAD

**Issue by diedriko** [allegro/ralph#3476]
./node_modules/.bin/gulp
assert.js:375
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/opt/ralph/ralph-20190627.1/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/opt/ralph/ralph-20190627.1/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/opt/ralph/ralph-20190627.1/gulpfile.js:140:6)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at execute (/opt/ralph/ralph-20190627.1/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

gulp -v
CLI version: 2.2.0
Local version: 4.0.2
 
node -v 
v12.6.0

**Comment by richlv** [comment]
Facing the same issue - gulp 3.x did not work with the latest node, gulp 4.0 gets the error as reported here.

Perhaps https://www.sitepoint.com/how-to-migrate-to-gulp-4/ is relevant.

**Comment by richlv** [comment]
Ralph does not support gulp4 - you'll have to force installation of gulp3.
