### ISSUE TITLE
500 error when using csv on /data_center/datacenterasset/process_import/

### ISSUE THREAD

**Issue by JustOneMoreDog** [allegro/ralph#3517]
### Steps to reproduce
Importing a csv file will cause a 500 error
Datacenter -> hardware -> import
Choose csv file 
it will show you a preview of the stuff that will be imported (its correct here) 
confirm import
get 500 error

### Expected behavior

Expected it to bulk import datacenter assets.  I was trying to do around 50 at once but I was also getting the same error when only do 3

### Actual behavior

Server Error (500)

### Environment

* Ralph version: Ralph-Core version: 20200129.1
* Operating system: Ubuntu 18.04.3 LTS 4.15.0-74-generic
* Method of installation: Deb package

**Comment by JustOneMoreDog** [comment]
Replicable step by step to reproduce this issue
steps to reproduce 
create 2 test assets
search for newly made assets
export as csv
```
parent,parent_str,parent_management_ip,service_env,service_env_str,model,model_str,rack,rack_str,budget_info,budget_info_str,management_ip,id,created,modified,remarks,configuration_path,configuration_path_str,hostname,sn,barcode,niw,required_support,order_no,invoice_no,invoice_date,price,provider,depreciation_rate,force_depreciation,depreciation_end_date,buyout_date,task_url,property_of,property_of_str,start_usage,status,position,orientation,slot_no,firmware_version,bios_version,source,delivery_date,production_year,production_use_date,tags,tags_str
,,None,Infrastructure|Production,Infrastructure - Production,73,[ETC] blank template,5,WDC-B207-01 (WDC Museum/B207),,,None,497,2/17/2020 15:20,2/17/2020 15:20,,,,import-bug-test-00,123,,,0,,,,0,,25,0,,,,,,,2,10,1,,,,,,,,,
,,None,Infrastructure|Production,Infrastructure - Production,73,[ETC] blank template,74,WDC-309-01 (WDC Museum/309A),,,None,495,2/14/2020 19:29,2/14/2020 19:29,,,,bulk import test,,naniiiiiiii,,0,,,,0,,25,0,,,,,,,1,1,1,,,,,,,,,
```
open in excel
delete the 3rd row that contains the 2nd asset leaving just the first test asset 
change the following information to make the test import asset unique
id: 497 -> 498
hostname: import-bug-test-00 -> import-bug-test-01
sn: 123 -> 1234
position: 10 -> 20
save the file still as a csv and with the new name of DataCenterAsset-2020-02-17-01
```
parent,parent_str,parent_management_ip,service_env,service_env_str,model,model_str,rack,rack_str,budget_info,budget_info_str,management_ip,id,created,modified,remarks,configuration_path,configuration_path_str,hostname,sn,barcode,niw,required_support,order_no,invoice_no,invoice_date,price,provider,depreciation_rate,force_depreciation,depreciation_end_date,buyout_date,task_url,property_of,property_of_str,start_usage,status,position,orientation,slot_no,firmware_version,bios_version,source,delivery_date,production_year,production_use_date,tags,tags_str
,,None,Infrastructure|Production,Infrastructure - Production,73,[ETC] blank template,5,WDC-B207-01 (WDC Museum/B207),,,None,498,2/17/2020 15:20,2/17/2020 15:20,,,,import-bug-test-01,1234,,,0,,,,0,,25,0,,,,,,,2,20,1,,,,,,,,,
```
close out of excel 
open the csv file up in notepad/notepad++ and confirm the data is still csv
visit /data_center/datacenterasset/import/
select the DataCenterAsset-2020-02-17-01.csv file and csv for format
confirm everything on the preview looks correct
![preview](https://user-images.githubusercontent.com/42121635/74663045-0bd2c600-5169-11ea-9a46-787e0a08022f.png)
press confirm import
get a Server Error (500) on /data_center/datacenterasset/process_import/

**Comment by JustOneMoreDog** [comment]
despite having found a solution I am going to keep this open because I do not feel that just a 500 error should be shown.  I ended up hoping onto the CLI and after reading the docs on how to import csv using ralph importer I was able to find the issue.  

The first thing I did was remove all the values from the ID column in hopes that Ralph would auto assign those values (it did).

```
motbadmin@templatevm_linux:~$ ralph importer --skipid --type file tester.csv --model_name DataCenterAsset
Import DataCenterAsset resource from tester.csv
ERROR:root:'None' does not appear to be an IPv4 or IPv6 address
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 379, in import_data
    self.save_m2m(instance, row, real_dry_run)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 251, in save_m2m
    self.import_field(field, obj, data)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 230, in import_field
    field.save(obj, data)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/fields.py", line 108, in save
    setattr(obj, attrs[-1], self.clean(data))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/data_center/models/mixins.py", line 89, in management_ip
    ip.save()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/networks/models/networks.py", line 758, in save
    self.number = int(ipaddress.ip_address(self.address or 0))
  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'None' does not appear to be an IPv4 or IPv6 address
line_number: 1
error message: 'None' does not appear to be an IPv4 or IPv6 address
row data: [('parent', ''), ('parent_str', ''), ('parent_management_ip', 'None'), ('service_env', 'Infrastructure|Production'), ('service_env_str', 'Infrastructure - Production'), ('model', '73'), ('model_str'
, '[ETC] blank template'), ('rack', '5'), ('rack_str', 'WDC-B207-01 (WDC Museum/B207)'), ('budget_info', ''), ('budget_info_str', ''), ('management_ip', 'None'), ('id', ''), ('created', '2/17/2020 15:20'), ('
modified', '2/17/2020 15:20'), ('remarks', ''), ('configuration_path', ''), ('configuration_path_str', ''), ('hostname', 'import-bug-test-01'), ('sn', '123412341234'), ('barcode', ''), ('niw', ''), ('required
_support', '0'), ('order_no', ''), ('invoice_no', ''), ('invoice_date', ''), ('price', '0'), ('provider', ''), ('depreciation_rate', '25'), ('force_depreciation', '0'), ('depreciation_end_date', ''), ('buyout
_date', ''), ('task_url', ''), ('property_of', ''), ('property_of_str', ''), ('start_usage', ''), ('status', '2'), ('position', '20'), ('orientation', '1'), ('slot_no', ''), ('firmware_version', ''), ('bios_v
ersion', ''), ('source', ''), ('delivery_date', ''), ('production_year', ''), ('production_use_date', ''), ('tags', ''), ('tags_str', '')]
Imported records: 1
0 deleted
Done
```

it seems that in my csv file I was having None for the management_ip.  After fixing this, I got another error

```
motbadmin@templatevm_linux:~$ ralph importer --skipid --type file tester.csv --model_name DataCenterAsset
Import DataCenterAsset resource from tester.csv
ERROR:root:(1048, "Column 'model_id' cannot be null")
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1048, "Column 'model_id' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 378, in import_data
    self.save_instance(instance, real_dry_run)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 195, in save_instance
    instance.save()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/data_center/models/physical.py", line 498, in save
    super().save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/assets/models/assets.py", line 543, in save
    return super(Asset, self).save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/lib/polymorphic/models.py", line 259, in save
    super().save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'model_id' cannot be null")
line_number: 2
error message: (1048, "Column 'model_id' cannot be null")
row data: []
Imported records: 0
0 deleted
Done
motbadmin@templatevm_linux:~$ ralph importer --skipid --type file tester.csv --model_name DataCenterAsset
Import DataCenterAsset resource from tester.csv
Imported records: 1
0 deleted
Done
```

This error was because I had an empty line at the end of the csv file.  I removed this line and got another error 

```
motbadmin@templatevm_linux:~$ ralph importer --skipid --type file tester.csv --model_name DataCenterAsset
Import DataCenterAsset resource from tester.csv
Imported records: 1
0 deleted
Done
motbadmin@templatevm_linux:~$ ralph importer --skipid --type file tester.csv --model_name DataCenterAsset
Import DataCenterAsset resource from tester.csv
ERROR:root:(1048, "Column 'force_depreciation' cannot be null")
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1048, "Column 'force_depreciation' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 378, in import_data
    self.save_instance(instance, real_dry_run)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/import_export/resources.py", line 195, in save_instance
    instance.save()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/data_center/models/physical.py", line 498, in save
    super().save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/assets/models/assets.py", line 543, in save
    return super(Asset, self).save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/lib/polymorphic/models.py", line 259, in save
    super().save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    six.reraise(utils.IntegrityError, utils.IntegrityError(*tuple(e.args)), sys.exc_info()[2])
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1048, "Column 'force_depreciation' cannot be null")
line_number: 1
error message: (1048, "Column 'force_depreciation' cannot be null")
row data: [('parent', ''), ('parent_str', ''), ('parent_management_ip', ''), ('service_env', 'Infrastructure|Production'), ('service_env_str', 'Infrastructure - Production'), ('model', '76'), ('model_str', '[Rack Accessory] SuperLogics Screen'), ('rack', '78'), ('rack_str', 'WDC-309-06 (WDC Museum/309A)'), ('budget_info', ''), ('budget_info_str', ''), ('management_ip', '')
, ('id', ''), ('created', '2020-02-14 22:05:15'), ('modified', '2020-02-14 22:05:15'), ('remarks', ''), ('configuration_path', ''), ('configuration_path_str', ''), ('hostname', 'WDC-309-06-SCREEN-01'), ('sn', 'IPM1001P1611123922'), ('barcode', ''), ('niw', ''), ('required_support', '0'), ('order_no', ''), ('invoice_no', ''), ('invoice_date', ''), ('price', '0'), ('provider
', ''), ('depreciation_rate', '25'), ('force_depreciation', ''), ('depreciation_end_date', ''), ('buyout_date', ''), ('task_url', ''), ('property_of', ''), ('property_of_str', ''), ('start_usage', ''), ('status', '2'), ('position', '29'), ('orientation', '1'), ('slot_no', ''), ('firmware_version', ''), ('bios_version', ''), ('source', ''), ('delivery_date', ''), ('producti
on_year', ''), ('production_use_date', ''), ('tags', ''), ('tags_str', '')]
Imported records: 0
0 deleted
Done
```

After I made sure the force_depreciation field was populated with 0s I redid the import and this time it worked.  I applied all of these fixes to my master csv file and was finally able to import the csv file

```
motbadmin@templatevm_linux:~$ ralph importer --skipid --type file tester.csv --model_name DataCenterAsset
Import DataCenterAsset resource from tester.csv
Imported records: 58
0 deleted
Done
```

Summary:
Leave the ID column blank
Dont have an extra empty line at the end of your csv file 
Make sure any of the IP Address based field are either empty or just an IP
Make sure the force_depreciation field is a number like 0 

As stated above, I am leaving this open because I think it would be a extremely useful for the GUI to spit out the above information.  If I had that information, I would have been able to troubleshoot.

**Comment by vi4m** [comment]
Thank you very much for detailed story about the issue. I think we should do better job showing import errors to the user.

**Comment by ssaklica** [comment]
![image](https://user-images.githubusercontent.com/61520068/81784782-0ab1fa80-9506-11ea-8283-bd498136a5b4.png)
I'have same issue about importing net Virual Machines.  it says blank is not accecptable. I tried  higher number last items id still no luck.
