### ISSUE TITLE
500 error when clicking on any datacenter asses

### ISSUE THREAD

**Issue by JustOneMoreDog** [allegro/ralph#3520]
### Steps to reproduce
trying to view any datacenter asset results in a 500 error both from the gui and from the api
/data_center/datacenterasset/224/

### Expected behavior

Expected it to show datacenter assets. 

### Actual behavior

Server Error (500)

### Environment

* Ralph version: Ralph-Core version: 20200129.1
* Operating system: Ubuntu 18.04.3 LTS 4.15.0-74-generic
* Method of installation: Deb package

**Comment by JustOneMoreDog** [comment]
I can reliably trigger this by simply using the API 

```
function ralph_asset_check {
        curl -s http://okc-ralph-01/api/data-center-assets/$1/ -H "Authorization: Token $(cat /home/user/.ralph_token)"
       echo ""
}
```

```
$ ralph_asset_check 425
<h1>Server Error (500)</h1>
```

By doing this I get the following error in /var/log/ralph/ralph.log

```
[20.02.2020 19:08:39,086] ERROR   [MainProcess 3268] base - Internal Server Error: /api/data-center-assets/425/
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1054, "Unknown column 'custom_fields_customfield.managing_group_id' in 'field list'")


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/rest_framework/mixins.py", line 56, in retrieve
    instance = self.get_object()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/rest_framework/generics.py", line 97, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/rest_framework/generics.py", line 20, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/shortcuts.py", line 155, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 967, in _fetch_all
    self._prefetch_related_objects()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 591, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, self._prefetch_related_lookups)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 1516, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 1615, in prefetch_one_level
    prefetcher.get_prefetch_queryset(instances, lookup.get_current_queryset(level)))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/lib/custom_fields/fields.py", line 326, in get_prefetch_queryset
    qs = list(queryset.filter(**query))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/lib/custom_fields/fields.py", line 136, in iterator
    yield from super().iterator()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'custom_fields_customfield.managing_group_id' in 'field list'")
```

I am able to import assets but I can not view them.  

```
$ ralph importer --verbosity 3 --skipid --type file 500_test_import.csv --model_name DataCenterAsset
Import DataCenterAsset resource from 500_test_import.csv
Imported records: 1
0 deleted
Done
```

It is worth noting that setting the `--verbosity 3` flag has no impact on the output of the command either

**Comment by vi4m** [comment]
Seems like a bug in https://github.com/allegro/ralph/commit/e93006480e446bfae029f9de066ca5e8926f07c8

**Comment by vi4m** [comment]
If you happen to upgrade Ralph recently, you should run `sudo ralphctl migrate` to apply changes to the database.

**Comment by klmyhd** [comment]
docker-compose run web init
docker-compose up -d
