### ISSUE TITLE
Error when adding a new license

### ISSUE THREAD

**Issue by juanpebalsa** [allegro/ralph#3603]
I get a Server Error (500) when trying to add a new license.

/var/log/ralph/ralph.log
```
28.01.2021 14:53:32,332] ERROR   [MainProcess 1032] base - Internal Server Error: /licences/licence/add/
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1364, "Field 'price_currency' doesn't have a default value")

```

* Ralph version: 20210119.1
* Operating system: Ubuntu 18.04
* Method of installation: Deb package

**Comment by juanpebalsa** [comment]
I get the same error when I try to add any new item:

```
[04.02.2021 13:46:19,397] ERROR   [MainProcess 1030] base - Internal Server Error: /data_center/datacenterasset/add/
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1364, "Field 'price_currency' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/reversion/revisions.py", line 297, in do_revision_context
    return func(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/admin/views/multiadd.py", line 191, in add_view
    return super().add_view(request, form_url, extra_context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1518, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/deployment/mixins.py", line 51, in changeform_view
    return super().changeform_view(request, object_id, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/lib/custom_fields/admin.py", line 136, in changeform_view
    request, object_id, form_url, extra_context
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/admin/mixins.py", line 343, in changeform_view
    request, object_id, form_url, extra_context
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1463, in changeform_view
    new_object = self.save_form(request, form, change=not add)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1074, in save_form
    return form.save(commit=False)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/data_center/forms.py", line 34, in save
    obj.save()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/data_center/models/physical.py", line 498, in save
    super().save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/assets/models/assets.py", line 544, in save
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/lib/polymorphic/models.py", line 259, in save
    super().save(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 761, in save_base
    self._save_parents(cls, using, update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 786, in _save_parents
    self._save_table(cls=parent, using=using, update_fields=update_fields)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 846, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 885, in _do_insert
    using=using, raw=raw)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 920, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 974, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1364, "Field 'price_currency' doesn't have a default value")
 ```
 
 
 It happens to me since I upgraded.

**Comment by juanpebalsa** [comment]
I have been able to solve it by running:
`ralphctl sitetree_resync_apps`

and then:
`systemctl restart ralph `
