### ISSUE TITLE
Delete user sends me Server Error (500)

### ISSUE THREAD

**Issue by TheFulmini** [allegro/ralph#3742]
Hello I have managed to run the app on OpenShift container platform.

### Steps to reproduce

Converting the Docker-compose file into yaml files usable by OpenShift I was able to run it on our Platform on our private network.
Everything works as expected. I can add users, machines, licences, etc... and i cant delete all of them except for users.

### Expected behavior

The user should be deleted and db updated without any issue

### Actual behavior

The user is not deleted and i receive a Server Error (500)

Error Logs: 

[27.10.2022 12:00:40,337] ERROR   [MainProcess 31] base - Internal Server Error: /accounts/ralphuser/3/delete/
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError: (1146, "Table 'ralph_ng.trade_marks_utilitymodel' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/options.py", line 618, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1709, in delete_view
    [obj], opts, request.user, self.admin_site, using)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 118, in get_deleted_objects
    collector.collect(objs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/utils.py", line 182, in collect
    return super(NestedObjects, self).collect(objs, source_attr=source_attr, **kwargs)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/deletion.py", line 228, in collect
    elif sub_objs:
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 166, in __bool__
    self._fetch_all()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
    rowcount = self._do_query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
    db.query(q)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.ProgrammingError: (1146, "Table 'ralph_ng.trade_marks_utilitymodel' doesn't exist")

### Environment

Running the solution on OpenShift Container Platform on a private network. We have 4 pods running for the project with 3 Persitent Volume Claims for the data 

* Ralph version:  3
* Operating system: Local Machine on Windows 11, Containers on OpenShift
* Method of installation: Docker/Kubernetes on OpenShift

**Comment by TheFulmini** [comment]
I have the same problem with domain deletion

**Comment by TheFulmini** [comment]
it looks like some tables are missing in my mysql db. 
here is the list of tables in the db.

I could add it manually but i would like to know which fields are necessary for this table.

+--------------------------------------------+
| Tables_in_ralph_ng                         |
+--------------------------------------------+
| access_cards_accesscard                    |
| access_cards_accesscard_access_zones       |
| access_cards_accesszone                    |
| accessories_accessory                      |
| accessories_accessoryuser                  |
| accounts_ralphuser                         |
| accounts_ralphuser_groups                  |
| accounts_ralphuser_regions                 |
| accounts_ralphuser_user_permissions        |
| accounts_region                            |
| accounts_team                              |
| assets_asset                               |
| assets_assetholder                         |
| assets_assetlasthostname                   |
| assets_assetmodel                          |
| assets_baseobject                          |
| assets_budgetinfo                          |
| assets_businesssegment                     |
| assets_category                            |
| assets_componentmodel                      |
| assets_configurationclass                  |
| assets_configurationmodule                 |
| assets_disk                                |
| assets_environment                         |
| assets_ethernet                            |
| assets_fibrechannelcard                    |
| assets_genericcomponent                    |
| assets_manufacturer                        |
| assets_manufacturerkind                    |
| assets_memory                              |
| assets_processor                           |
| assets_profitcenter                        |
| assets_service                             |
| assets_service_business_owners             |
| assets_service_technical_owners            |
| assets_serviceenvironment                  |
| attachments_attachment                     |
| attachments_attachmentitem                 |
| auth_group                                 |
| auth_group_permissions                     |
| auth_permission                            |
| authtoken_token                            |
| back_office_backofficeasset                |
| back_office_officeinfrastructure           |
| back_office_warehouse                      |
| configuration_management_scmstatuscheck    |
| custom_fields_customfield                  |
| custom_fields_customfieldvalue             |
| dashboards_dashboard                       |
| dashboards_dashboard_graphs                |
| dashboards_graph                           |
| data_center_accessory                      |
| data_center_baseobjectcluster              |
| data_center_cluster                        |
| data_center_clustertype                    |
| data_center_connection                     |
| data_center_database                       |
| data_center_datacenter                     |
| data_center_datacenterasset                |
| data_center_diskshare                      |
| data_center_disksharemount                 |
| data_center_rack                           |
| data_center_rackaccessory                  |
| data_center_serverroom                     |
| data_center_vip                            |
| data_importer_importedobjects              |
| deployment_preboot                         |
| deployment_preboot_items                   |
| deployment_prebootconfiguration            |
| deployment_prebootfile                     |
| deployment_prebootitem                     |
| dhcp_dhcpserver                            |
| dhcp_dnsserver                             |
| dhcp_dnsservergroup                        |
| dhcp_dnsservergrouporder                   |
| django_admin_log                           |
| django_content_type                        |
| django_migrations                          |
| django_session                             |
| domains_dnsprovider                        |
| domains_domain                             |
| domains_domain_additional_services         |
| domains_domaincategory                     |
| domains_domaincontract                     |
| domains_domainprovideradditionalservices   |
| domains_domainregistrant                   |
| external_services_job                      |
| licences_baseobjectlicence                 |
| licences_licence                           |
| licences_licencetype                       |
| licences_licenceuser                       |
| licences_software                          |
| networks_discoveryqueue                    |
| networks_ipaddress                         |
| networks_network                           |
| networks_network_racks                     |
| networks_network_terminators               |
| networks_networkenvironment                |
| networks_networkkind                       |
| operations_operation                       |
| operations_operation_base_objects          |
| operations_operationstatus                 |
| operations_operationtype                   |
| reports_report                             |
| reports_reportlanguage                     |
| reports_reporttemplate                     |
| reversion_revision                         |
| reversion_version                          |
| security_securityscan                      |
| security_securityscan_vulnerabilities      |
| security_vulnerability                     |
| sim_cards_cellularcarrier                  |
| sim_cards_simcard                          |
| sim_cards_simcard_features                 |
| sim_cards_simcardfeatures                  |
| sitetree_tree                              |
| sitetree_treeitem                          |
| sitetree_treeitem_access_permissions       |
| ssl_certificates_sslcertificate            |
| supports_baseobjectssupport                |
| supports_support                           |
| supports_supporttype                       |
| taggit_tag                                 |
| taggit_taggeditem                          |
| trade_marks_design                         |
| trade_marks_design_additional_markings     |
| trade_marks_designadditionalcountry        |
| trade_marks_designslinkeddomains           |
| trade_marks_patent                         |
| trade_marks_patent_additional_markings     |
| trade_marks_patentadditionalcountry        |
| trade_marks_patentslinkeddomains           |
| trade_marks_provideradditionalmarking      |
| trade_marks_trademark                      |
| trade_marks_trademark_additional_markings  |
| trade_marks_trademarkadditionalcountry     |
| trade_marks_trademarkcountry               |
| trade_marks_trademarkkind                  |
| trade_marks_trademarkregistrarinstitution  |
| trade_marks_trademarkslinkeddomains        |
| transitions_action                         |
| transitions_action_content_type            |
| transitions_transition                     |
| transitions_transition_actions             |
| transitions_transitionjob                  |
| transitions_transitionjobaction            |
| transitions_transitionmodel                |
| transitions_transitionshistory             |
| transitions_transitionshistory_attachments |
| virtual_cloudflavor                        |
| virtual_cloudhost                          |
| virtual_cloudimage                         |
| virtual_cloudproject                       |
| virtual_cloudprovider                      |
| virtual_virtualcomponent                   |
| virtual_virtualserver                      |
| virtual_virtualservertype                  |
+--------------------------------------------+



Thanks a lot

**Comment by TheFulmini** [comment]
i was just missing the latest migration silly me
