### ISSUE TITLE
server error 500 fresh install

### ISSUE THREAD

**Issue by screwyluie** [allegro/ralph#3748]
cloned the repo, copied the docker-compose.yml, made one change to the nginx port. Follow the install instructions.

page is up, login ralph:ralph
Server error 500

```
web_1    | [06.01.2023 02:45:14,904] ERROR   [MainProcess 32] base - Internal Server Error: /login/
web_1    | Traceback (most recent call last):
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
web_1    |     return self.cursor.execute(query, args)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
web_1    |     self.errorhandler(self, exc, value)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
web_1    |     raise errorvalue
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
web_1    |     res = self._query(query)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
web_1    |     rowcount = self._do_query(q)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
web_1    |     db.query(q)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
web_1    |     _mysql.connection.query(self, query)
web_1    | _mysql_exceptions.ProgrammingError: (1146, "Table 'ralph_ng.accounts_ralphuser' doesn't exist")
web_1    |
web_1    | The above exception was the direct cause of the following exception:
web_1    |
web_1    | Traceback (most recent call last):
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/handlers/base.py", line 132, in get_response
web_1    |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1    |   File "/usr/lib/python3.6/contextlib.py", line 52, in inner
web_1    |     return func(*args, **kwds)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 400, in login
web_1    |     return login(request, **defaults)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
web_1    |     return view(request, *args, **kwargs)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
web_1    |     response = view_func(request, *args, **kwargs)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/auth/views.py", line 44, in login
web_1    |     if form.is_valid():
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/forms/forms.py", line 184, in is_valid
web_1    |     return self.is_bound and not self.errors
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/forms/forms.py", line 176, in errors
web_1    |     self.full_clean()
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/forms/forms.py", line 393, in full_clean
web_1    |     self._clean_form()
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/forms/forms.py", line 417, in _clean_form
web_1    |     cleaned_data = self.clean()
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/auth/forms.py", line 157, in clean
web_1    |     password=password)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 74, in authenticate
web_1    |     user = backend.authenticate(**credentials)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 17, in authenticate
web_1    |     user = UserModel._default_manager.get_by_natural_key(username)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/contrib/auth/models.py", line 162, in get_by_natural_key
web_1    |     return self.get(**{self.model.USERNAME_FIELD: username})
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/manager.py", line 127, in manager_method
web_1    |     return getattr(self.get_queryset(), name)(*args, **kwargs)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 328, in get
web_1    |     num = len(clone)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 144, in __len__
web_1    |     self._fetch_all()
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 965, in _fetch_all
web_1    |     self._result_cache = list(self.iterator())
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/query.py", line 238, in iterator
web_1    |     results = compiler.execute_sql()
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
web_1    |     cursor.execute(sql, params)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 98, in __exit__
web_1    |     six.reraise(dj_exc_type, dj_exc_value, traceback)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
web_1    |     raise value.with_traceback(tb)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
web_1    |     return self.cursor.execute(sql, params)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 124, in execute
web_1    |     return self.cursor.execute(query, args)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
web_1    |     self.errorhandler(self, exc, value)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
web_1    |     raise errorvalue
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
web_1    |     res = self._query(query)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
web_1    |     rowcount = self._do_query(q)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
web_1    |     db.query(q)
web_1    |   File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
web_1    |     _mysql.connection.query(self, query)
web_1    | django.db.utils.ProgrammingError: (1146, "Table 'ralph_ng.accounts_ralphuser' doesn't exist")
```

**Comment by lazysecurityguy** [comment]
Hi, I have had the some issue and solve it by this command to init database:
`docker-compose run --rm web init`
[Docs fix commit](https://github.com/allegro/ralph/pull/3403/commits/5ee834b7e01da36e8180828f5c6580e9df50b501)

**Comment by screwyluie** [comment]
> Hi, I have had the some issue and solve it by this command to init database: `docker-compose run --rm web init` [Docs fix commit](https://github.com/allegro/ralph/pull/3403/commits/5ee834b7e01da36e8180828f5c6580e9df50b501)

pure gold, thank you. This worked.
