### ISSUE TITLE
Stop releasing broken software

### ISSUE THREAD

**Issue by Silex** [allegro/ralph#3833]
https://github.com/allegro/ralph/blob/ng/docker/ is outdated & broken.
https://ralph-ng.readthedocs.io/en/stable/installation/installation/ is outdated & broken.

```
root@a77a4d08c144:/# ralphctl migrate
Traceback (most recent call last):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
    return import_module('%s.base' % backend_name)
  File "/opt/ralph/ralph-core/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transaction_hooks'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ralph/ralph-core/bin/ralph", line 8, in <module>
    sys.exit(prod())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/__main__.py", line 28, in prod
    main('ralph.settings.prod')
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/ralph/__main__.py", line 14, in main
    execute_from_command_line(sys.argv)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/ralph/ralph-core/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/taggit/models.py", line 21, in <module>
    class TagBase(models.Model):
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 119, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/base.py", line 316, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/django/db/utils.py", line 134, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'transaction_hooks.backends.mysql' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql', 'sqlite3'
Error was: No module named 'transaction_hooks'
```

Doing releases is meaningless if one cannot install your software.

@hipek8, @matyldv you guys should make a statement somewhere saying that the work you do on this repo is not meant to be used. Your activity gives a false sense of... activity, but it looks like the work you do here is only useful to Allegro internally.

**Comment by vi4m** [comment]
@Silex did you read the README.md statement?  It’s super clear.

Also, the team is busy upgrading Django, that’s the main goal, and made a lot of progress last months.  Documentation is not yet updated and we make not guarantess. Again, read the README file.

**Comment by Silex** [comment]
@vi4m 

> Effective January 1, 2024, all development and maintenance activities associated with the Ralph project on Allegro's GitHub will be discontinued. This means that no further updates or modifications will be applied to the codebase.

I see a lot of "further updates & modifications", which contradicts that statements and gives a false impression of activity/support.

Your statement "the team is busy upgrading Django" also implies activity. But each release you do is broken as we cannot install the software. So I guess these releases are only useful to you.

If only you tagged the latest stable release, maybe people could give the software a try. I tried the 20230926.1, it installs but then many things in the UI are broken.

**Comment by Silex** [comment]
> However, this development will not be publicly accessible, and any updates or modifications made by Allegro will not reflect in the community version of the code

Again not what you are doing.

> we encourage the community to persist in utilizing and expanding upon the codebase in the years ahead.

It's hard to participate when basic communication is missing. You'd add the following to the README:

- Current version is broken, latest stable is tag XYZ.
- Current activity is for internal use and might result in a newer stable release, without guarantee.
- Issue tracker / discourse / discussions are ignored.

**Comment by vi4m** [comment]
We’re not giving up on Ralph yet. That’s why we’re checking if we can upgrade it to the new version od Django, which is quite complex project. 

We can’t make any promises so far yet but a lot has been done https://github.com/allegro/ralph/pull/3815 https://github.com/allegro/ralph/pull/3813

**Comment by vi4m** [comment]
Closing this.

**Comment by Silex** [comment]
So, there's no old-but-stable version to use that you can mention?
